//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Peek.ImportWebJob {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Peek.ImportWebJob.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the azureusage table existed it was deleted..
        /// </summary>
        public static string AzureUsageTableCleanupMessage {
            get {
                return ResourceManager.GetString("AzureUsageTableCleanupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the customers table existed it was deleted..
        /// </summary>
        public static string CustomersTableCleanupMessage {
            get {
                return ResourceManager.GetString("CustomersTableCleanupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PartitionKey property must be populated to perform this operation..
        /// </summary>
        public static string NoPartitionKeyException {
            get {
                return ResourceManager.GetString("NoPartitionKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RowKey property must be populated to perform this operation..
        /// </summary>
        public static string NoRowKeyException {
            get {
                return ResourceManager.GetString("NoRowKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeping for one minute in order to avoid any processing issues..
        /// </summary>
        public static string SleepMessage {
            get {
                return ResourceManager.GetString("SleepMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the subscriptions queue existed it was deleted..
        /// </summary>
        public static string SubscriptionsQueueCleanupMessage {
            get {
                return ResourceManager.GetString("SubscriptionsQueueCleanupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the subscriptions table existed it was deleted..
        /// </summary>
        public static string SubscriptionsTableCleanupMessage {
            get {
                return ResourceManager.GetString("SubscriptionsTableCleanupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the usage container existed it was deleted..
        /// </summary>
        public static string UsageContainerCleanupMessage {
            get {
                return ResourceManager.GetString("UsageContainerCleanupMessage", resourceCulture);
            }
        }
    }
}
